package com.deha.HumanResourceManagement.entity.enums;

public enum Permission {
    USER_VIEW,
    USER_MANAGE,
    DEPARTMENT_VIEW,
    DEPARTMENT_MANAGE,
    POSITION_VIEW,
    POSITION_MANAGE,
    OFFICE_VIEW,
    OFFICE_MANAGE,
    OFFICE_POLICY_VIEW,
    OFFICE_POLICY_UPDATE,
    SALARY_CONTRACT_VIEW,
    SALARY_CONTRACT_MANAGE,
    PAYROLL_VIEW,
    PAYROLL_GENERATE,
    OT_REQUEST_APPROVAL_VIEW,
    OT_REQUEST_APPROVE,
    OT_REPORT_APPROVAL_VIEW,
    OT_REPORT_APPROVE
}

