server:
  port: 8081

spring:
  application:
    name: HumanResourceManagement

  datasource:
    url: jdbc:postgresql://localhost:5432/HRM
    username: postgres
    password: postgre
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect