ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE chat_rooms ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE chat_rooms ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE departments ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE departments ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE offices ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE offices ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE office_wifi_ips ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE office_wifi_ips ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE ot_requests ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE ot_requests ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE ot_reports ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE ot_reports ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE ot_sessions ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE ot_sessions ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE payrolls ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE payrolls ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE positions ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE positions ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE salary_contracts ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE salary_contracts ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

