name: Build and Deploy (OIDC - Final)

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

  RESOURCE_GROUP: hrm-deha-resource

  BACKEND_APP: hrm-deha
  FRONTEND_APP: hrm-fe-deha

  BACKEND_URL: https://hrm-deha-cjhwf4c0egg0feg2.malaysiawest-01.azurewebsites.net
  FRONTEND_URL: https://hrm-fe-deha-gwdqenfph5f2ewb9.malaysiawest-01.azurewebsites.net

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login --name $(echo $ACR_LOGIN_SERVER | cut -d'.' -f1)

      - name: Build & Push Backend
        run: |
          docker build -t $ACR_LOGIN_SERVER/backend:${{ github.sha }} ./backend
          docker push $ACR_LOGIN_SERVER/backend:${{ github.sha }}

      - name: Build & Push Frontend
        run: |
          docker build -t $ACR_LOGIN_SERVER/frontend:${{ github.sha }} ./frontend
          docker push $ACR_LOGIN_SERVER/frontend:${{ github.sha }}

      - name: Get current backend image
        id: old_backend
        run: |
          OLD=$(az webapp config container show \
            --name $BACKEND_APP \
            --resource-group $RESOURCE_GROUP \
            --query "linuxFxVersion" -o tsv)
          echo "old_image=$OLD" >> $GITHUB_OUTPUT

      - name: Deploy Backend
        run: |
          az webapp config container set \
            --name $BACKEND_APP \
            --resource-group $RESOURCE_GROUP \
            --container-image-name $ACR_LOGIN_SERVER/backend:${{ github.sha }} \
            --container-registry-url https://$ACR_LOGIN_SERVER

      - name: Restart Backend
        run: |
          az webapp restart \
            --name $BACKEND_APP \
            --resource-group $RESOURCE_GROUP

      - name: Health Check Backend
        run: |
          echo "Waiting for backend..."
          sleep 25
          curl -f $BACKEND_URL/actuator/health

      - name: Get current frontend image
        id: old_frontend
        run: |
          OLD=$(az webapp config container show \
            --name $FRONTEND_APP \
            --resource-group $RESOURCE_GROUP \
            --query "linuxFxVersion" -o tsv)
          echo "old_image=$OLD" >> $GITHUB_OUTPUT

      - name: Deploy Frontend
        run: |
          az webapp config container set \
            --name $FRONTEND_APP \
            --resource-group $RESOURCE_GROUP \
            --container-image-name $ACR_LOGIN_SERVER/frontend:${{ github.sha }} \
            --container-registry-url https://$ACR_LOGIN_SERVER

      - name: Restart Frontend
        run: |
          az webapp restart \
            --name $FRONTEND_APP \
            --resource-group $RESOURCE_GROUP

      - name: Health Check Frontend
        run: |
          echo "Waiting for frontend..."
          sleep 20
          curl -f $FRONTEND_URL

      - name: Rollback Backend
        if: failure()
        run: |
          echo "Rolling back backend..."
          az webapp config container set \
            --name $BACKEND_APP \
            --resource-group $RESOURCE_GROUP \
            --container-image-name "${{ steps.old_backend.outputs.old_image }}"
          az webapp restart \
            --name $BACKEND_APP \
            --resource-group $RESOURCE_GROUP

      - name: Rollback Frontend
        if: failure()
        run: |
          echo "Rolling back frontend..."
          az webapp config container set \
            --name $FRONTEND_APP \
            --resource-group $RESOURCE_GROUP \
            --container-image-name "${{ steps.old_frontend.outputs.old_image }}"
          az webapp restart \
            --name $FRONTEND_APP \
            --resource-group $RESOURCE_GROUP
